package com.neurogrid.simulation;

import junit.framework.TestCase;
// JUnitDoclet begin import
import com.neurogrid.simulation.AdversarialNode;
import com.neurogrid.simulation.SimpleDocument;
import com.neurogrid.simulation.SimpleContentMessage;
import com.neurogrid.simulation.SimpleKeyword;
import com.neurogrid.simulation.root.ContentMessage;
import com.neurogrid.simulation.root.Node;
import com.neurogrid.simulation.root.Keyword;
import com.neurogrid.simulation.root.Document;
import junit.framework.TestSuite;
import java.util.Set;
import java.util.Random;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class AdversarialNodeTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.neurogrid.simulation.AdversarialNode adversarialnode = null;
  com.neurogrid.simulation.AdversarialNetwork adversarialnetwork = null;
  
  /**
 * @param name  the name of the test
 */
  public AdversarialNodeTest(String name) {
    // JUnitDoclet begin method AdversarialNodeTest
    super(name);
    AdversarialNode.init(System.getProperty("Log4jConfig"));
    // JUnitDoclet end method AdversarialNodeTest
  }
  
  public com.neurogrid.simulation.AdversarialNode createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    adversarialnetwork = new AdversarialNetwork();
    return new com.neurogrid.simulation.AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    adversarialnode = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    adversarialnode = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetCvsInfo() throws Exception {
    // JUnitDoclet begin method getCvsInfo
    // JUnitDoclet end method getCvsInfo
  }
  
  public void testInit() throws Exception {
    // JUnitDoclet begin method init
    // JUnitDoclet end method init
  }
  
  public void testGetNewNodeID() throws Exception {
    // JUnitDoclet begin method getNewNodeID
    // JUnitDoclet end method getNewNodeID
  }
  
  public void testToString() throws Exception {
    // JUnitDoclet begin method toString
    // JUnitDoclet end method toString
  }
  
  public void testAddMessageToInbox() throws Exception {
    // JUnitDoclet begin method addMessageToInbox
    
    Keyword[] x_keywords = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	
     
    Document x_doc = new SimpleDocument(x_keywords);
    Node x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);
    adversarialnode.addMessageToInbox(x_message);
    assertTrue("message location not updated",x_message.getLocation() == adversarialnode);
    assertTrue("message of correct type not in inbox",
               adversarialnode.inboxContainsMessage(x_message).equals("com.neurogrid.simulation.SimpleContentMessage"));
    // JUnitDoclet end method addMessageToInbox
  }
  
  public void testDoGraphics() throws Exception {
    // JUnitDoclet begin method doGraphics
    // JUnitDoclet end method doGraphics
  }
  
  public void testDoGraphics2() throws Exception {
    // JUnitDoclet begin method doGraphics2
    // JUnitDoclet end method doGraphics2
  }
  
  public void testProcessMessage() throws Exception {
    // JUnitDoclet begin method processMessage
    // JUnitDoclet end method processMessage
  }
  
  public void testSetInactive() throws Exception {
    // JUnitDoclet begin method setInactive
    assertTrue("node already active",!adversarialnode.getActive());
    
    adversarialnode.setActive();
    
    assertTrue("node not active",adversarialnode.getActive());
    assertTrue("node not added to active set",adversarialnetwork.activeNodeContains(adversarialnode));
    
    adversarialnode.setInactive();
    
    assertTrue("node not inactive",!adversarialnode.getActive());
    assertTrue("node still in active set",!adversarialnetwork.activeNodeContains(adversarialnode));
    // JUnitDoclet end method setInactive
  }
  
  public void testSetActive() throws Exception {
    // JUnitDoclet begin method setActive
    assertTrue("node already active",!adversarialnode.getActive());
    
    adversarialnode.setActive();
    
    assertTrue("node not active",adversarialnode.getActive());
    assertTrue("node not added to active set",adversarialnetwork.activeNodeContains(adversarialnode));
    // JUnitDoclet end method setActive
  }
  
  public void testGetActive() throws Exception {
    // JUnitDoclet begin method getActive
    // JUnitDoclet end method getActive
  }
  
  public void testGetNodeID() throws Exception {
    // JUnitDoclet begin method getNodeID
    // JUnitDoclet end method getNodeID
  }
  
  public void testGetNoConnections() throws Exception {
    // JUnitDoclet begin method getNoConnections
    // JUnitDoclet end method getNoConnections
  }
  
  public void testGetNoContents() throws Exception {
    // JUnitDoclet begin method getNoContents
    // JUnitDoclet end method getNoContents
  }
  
  public void testGetNoKnowledge() throws Exception {
    // JUnitDoclet begin method getNoKnowledge
    // JUnitDoclet end method getNoKnowledge
  }
  
  public void testGetTotalNoKnowledge() throws Exception {
    // JUnitDoclet begin method getTotalNoKnowledge
    // JUnitDoclet end method getTotalNoKnowledge
  }
  
  public void testCheckInbox() throws Exception {
    // JUnitDoclet begin method checkInbox
    // JUnitDoclet end method checkInbox
  }
  
  public void testClearInbox() throws Exception {
    // JUnitDoclet begin method clearInbox
    Keyword[] x_keywords = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	
     
    Document x_doc = new SimpleDocument(x_keywords);
    Node x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);
    adversarialnode.addMessageToInbox(x_message);
    assertTrue("message location not updated",x_message.getLocation() == adversarialnode);
    assertTrue("message of correct type not in inbox",
                adversarialnode.inboxContainsMessage(x_message).equals("com.neurogrid.simulation.SimpleContentMessage"));

    assertTrue("checkInbox indicates inbox empty",adversarialnode.checkInbox());
    
    adversarialnode.clearInbox();
    
    assertTrue("checkInbox indicated inbox full",!adversarialnode.checkInbox());
    
    // JUnitDoclet end method clearInbox
  }
  
    
  public void testCheckSeen() throws Exception {
    // JUnitDoclet begin method checkInbox
    Keyword[] x_keywords = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	
     
    Document x_doc = new SimpleDocument(x_keywords);
    Node x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);
    ContentMessage x_message2 = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);
    adversarialnode.addToSeen(x_message); 
    assertTrue("seen message not indicated as such",adversarialnode.checkSeen(x_message)!=null);
    assertTrue("unseen messageindicated as seen",adversarialnode.checkSeen(x_message2)==null);
    
    
    // JUnitDoclet end method checkInbox
  }
  
  public void testClearGUIDs() throws Exception {
    // JUnitDoclet begin method clearGUIDs
    
    Keyword[] x_keywords = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	
     
    Document x_doc = new SimpleDocument(x_keywords);
    Node x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);
    adversarialnode.addToSeen(x_message);    
    assertTrue("seen message not indicated as such",adversarialnode.checkSeen(x_message)!=null);
    adversarialnode.clearGUIDs();    
    assertTrue("message indicated as seen after cleared",adversarialnode.checkSeen(x_message)==null);
    assertTrue("not all messages cleared",adversarialnode.getNoSeenMessages() == 0);
    
    // JUnitDoclet end method clearGUIDs
  }
  
  public void testClearConnList() throws Exception {
    // JUnitDoclet begin method clearConnList
    
   AdversarialNode x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    
    adversarialnode.addConnection(x_node);
    
    assertTrue("failed to add connection",adversarialnode.hasConnection(x_node));
    
    adversarialnode.clearConnList();
    
    assertTrue("clear failed to remove connection",!adversarialnode.hasConnection(x_node));
    assertTrue("no. conns not zero",adversarialnode.getNoConnections() == 0);
    
    
    // JUnitDoclet end method clearConnList
  }
  
  public void testClearContents() throws Exception {
    // JUnitDoclet begin method clearContents
    
    SimpleDocument x_doc = new SimpleDocument(3);
    
    adversarialnode.addContent(x_doc);
    
    assertTrue("content not added",adversarialnode.hasContent(x_doc));    
    
    adversarialnode.clearContents();
    
    assertTrue("node failing to still claim contents",adversarialnode.hasContent(x_doc));
    assertTrue("no. content not zero",adversarialnode.getNoContents() == 0);
    
    // JUnitDoclet end method clearContents
  }

  public void testGetConnList() throws Exception {
    // JUnitDoclet begin method getConnList
    // JUnitDoclet end method getConnList
  }
  
  public void testAllKeywords() throws Exception {
    // JUnitDoclet begin method allKeywords
    // JUnitDoclet end method allKeywords
  }
  
  public void testAddConnection() throws Exception {
    // JUnitDoclet begin method addConnection
    
    try
    {
      adversarialnode.addConnection(null);
      fail("Failed to throw exception when adding null connection");	
    }
    catch(Exception e){}

    AdversarialNode x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    
    adversarialnode.addConnection(x_node);
    
    assertTrue(adversarialnode.hasConnection(x_node));
    
    
    // JUnitDoclet end method addConnection
  }
  
  public void testHasConnection() throws Exception {
    // JUnitDoclet begin method hasConnection
    try
    {
      adversarialnode.hasConnection(null);
      fail("Failed to throw exception when checking for null connection");	
    }
    catch(Exception e){}
        
    AdversarialNode x_node = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    AdversarialNode x_node2 = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    
    adversarialnode.addConnection(x_node);
    
    assertTrue(adversarialnode.hasConnection(x_node));
    assertTrue(!adversarialnode.hasConnection(x_node2));
    
    // JUnitDoclet end method hasConnection
  }
  
  public void testAddContent() throws Exception {
    // JUnitDoclet begin method addContent
    
    try
    {
      adversarialnode.addContent(null);
      fail("Failed to throw exception when adding null content");	
    }
    catch(Exception e){}

    SimpleDocument x_doc = new SimpleDocument(3);
    
    adversarialnode.addContent(x_doc);
    
    assertTrue(adversarialnode.hasContent(x_doc));    
    // JUnitDoclet end method addContent
  }
  
  public void testHasContent() throws Exception {
    // JUnitDoclet begin method hasContent
    
    try
    {
      adversarialnode.hasContent(null);
      fail("Failed to throw exception when checking for null content");	
    }
    catch(Exception e){}

    SimpleDocument x_doc = new SimpleDocument(3);
    SimpleDocument x_doc2 = new SimpleDocument(3);
    
    adversarialnode.addContent(x_doc);
    
    assertTrue("node claims no content when it should always claim content",adversarialnode.hasContent(x_doc));    
    assertTrue("node failed to claim not present content, but it should",adversarialnode.hasContent(x_doc2));    
    // JUnitDoclet end method hasContent
  }
  
  public void testHasKeyword() throws Exception {
    // JUnitDoclet begin method hasContent
    
    try
    {
      adversarialnode.hasKeyword(null);
      fail("Failed to throw exception when checking for null content");	
    }
    catch(Exception e){}

    Keyword[] x_keywords = new SimpleKeyword[3];
    Keyword[] x_keywords2 = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
      x_keywords2[i] = new SimpleKeyword();	
    }	

    SimpleDocument x_doc = new SimpleDocument(x_keywords);
    SimpleDocument x_doc2 = new SimpleDocument(x_keywords2);
    
    adversarialnode.addContent(x_doc);

    for(int i=0;i<3;i++)
    {    
      assertTrue("local keyword not indicated",adversarialnode.hasKeyword(x_keywords[i]) == 1);    
      assertTrue("absent keyword identified as local",adversarialnode.hasKeyword(x_keywords2[i]) == 0); 
    }   
    // JUnitDoclet end method hasContent
  }
  
  public void testMatchingDocuments() throws Exception {
    // JUnitDoclet begin method matchingDocuments

    try
    {
      adversarialnode.matchingDocuments(null);
      fail("Failed to throw exception when checking for null content");	
    }
    catch(Exception e){}

    Keyword[] x_keywords = new SimpleKeyword[3];
    Keyword[] x_keywords2 = new SimpleKeyword[3];
    Keyword[] x_keywords3 = new SimpleKeyword[3];
    
    for(int i=0;i<3;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
      x_keywords2[i] = new SimpleKeyword();	
      x_keywords3[i] = new SimpleKeyword();	
    }	

    SimpleDocument x_doc = new SimpleDocument(x_keywords);
    SimpleDocument x_doc2 = new SimpleDocument(x_keywords);
    SimpleDocument x_doc3 = new SimpleDocument(x_keywords2);
    
    adversarialnode.addContent(x_doc);
    adversarialnode.addContent(x_doc2);
    adversarialnode.addContent(x_doc3);

    Set x_set = adversarialnode.matchingDocuments(x_keywords);
    
    assertTrue("node not claiming all possible docs",x_set.size()==3);
    assertTrue("x_doc not found",x_set.contains(x_doc));
    assertTrue("xdoc2 not found",x_set.contains(x_doc2));
    assertTrue("xdoc3 claimed absent when even absent docs should be claimed",x_set.contains(x_doc3));

    // added the following in order to expose NullPointerException error
    // in Node.java - i.e. the following operation
    //      x_docs = (Vector)(o_contents.get(p_keywords[i]));
    //      x_set.addAll(x_docs);
    x_set = adversarialnode.matchingDocuments(x_keywords3);
    assertTrue("failed to clain match from unrelated keywords",x_set.size()==3);


    // JUnitDoclet end method matchingDocuments
  }
  
  public void testMatchingKeywords() throws Exception {
    // JUnitDoclet begin method matchingKeywords
    // JUnitDoclet end method matchingKeywords
  }
  
  public void testGetContent() throws Exception {
    // JUnitDoclet begin method getContent
    // JUnitDoclet end method getContent
  }
  
  public void testGetContentsByDocID() throws Exception {
    // JUnitDoclet begin method getContentsByDocID
    // JUnitDoclet end method getContentsByDocID
  }
  
  public void testGetRandomContent() throws Exception {
    // JUnitDoclet begin method getRandomContent
    // JUnitDoclet end method getRandomContent
  }
  
  public void testGetRandomKeyword() throws Exception {
    // JUnitDoclet begin method getRandomKeyword
    // JUnitDoclet end method getRandomKeyword
  }
  
  public void testAddKnowledge() throws Exception {
    // JUnitDoclet begin method addKnowledge
    // JUnitDoclet end method addKnowledge
  }
  
  public void testGetRecommendation() throws Exception {
    // JUnitDoclet begin method getRecommendation
    // JUnitDoclet end method getRecommendation
  }
  
  public void testHandleMessage() throws Exception {
 // JUnitDoclet begin method handleMessage
    SimpleKeyword[][] x_keywords = new SimpleKeyword[3][3];
    
    for(int i=0;i<3;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new SimpleContentMessage[3];
    
    Node x_node[] = new AdversarialNode[4];
    for(int i=0;i<4;i++)
    {
      x_node[i] = new AdversarialNode(adversarialnetwork,new GnutellaMessageHandler(new Random(888)));
    }
    
    
    adversarialnode.addConnection(x_node[1]);
    adversarialnode.addConnection(x_node[2]);
    adversarialnode.addConnection(x_node[3]);
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_keywords[k]);	
      x_message[k] = new SimpleContentMessage(3,x_doc[k].getKeywords(),x_doc[k],x_node[3]);
      x_message[k].setPreviousLocation(x_node[3]);
    }
    
    adversarialnode.addContent(x_doc[0]);  
    
    assertTrue("failed to successfully handle message",
               adversarialnode.handleMessage(x_message[1]));

    assertTrue("node not activated",adversarialnode.getActive());

    assertTrue("Connected Node failed to receive message of correct type",
               x_node[1].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.SimpleContentMessage"));
    assertTrue("Connected Node failed to receive message of correct type",
               x_node[2].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.SimpleContentMessage"));
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message[1]) == null);
    assertTrue("initial node still has message",
               adversarialnode.inboxContainsMessage(x_message[1]) == null);


// JUnitDoclet end method handleMessage 
  }
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault

    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    String x_method = System.getProperty("test.method");
    System.out.println("test.method="+x_method);
    if(x_method == null || x_method.equals(""))
    {
      System.out.println("testing all methods");
    
      junit.textui.TestRunner.run(AdversarialNodeTest.class);
    }
    else
    {
      System.out.println("testing single method");

      TestSuite suite = new TestSuite();
      suite.addTest(new AdversarialNodeTest(x_method));
      junit.textui.TestRunner.run(suite);
    }    // JUnitDoclet end method testcase.main
  }
}
