package com.neurogrid.simulation;

import java.util.Random;

import junit.framework.TestCase;
import junit.framework.TestSuite;

import com.neurogrid.simulation.root.ContentMessage;
import com.neurogrid.simulation.root.Keyword;
import com.neurogrid.simulation.root.Network;
import com.neurogrid.simulation.root.Node;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class NeuroGridMessageHandlerTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  com.neurogrid.simulation.NeuroGridMessageHandler neurogridmessagehandler = null;
  com.neurogrid.simulation.NeuroGridNetwork neurogridnetwork = null;
  // JUnitDoclet end class
  
  public NeuroGridMessageHandlerTest(String name) {
    // JUnitDoclet begin method NeuroGridMessageHandlerTest
    super(name);
    NeuroGridMessageHandler.init(System.getProperty("Log4jConfig"));
    // JUnitDoclet end method NeuroGridMessageHandlerTest
  }
  
  public com.neurogrid.simulation.NeuroGridMessageHandler createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    neurogridnetwork = new NeuroGridNetwork();
    return new com.neurogrid.simulation.NeuroGridMessageHandler(new Random(888));
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    neurogridmessagehandler = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    neurogridmessagehandler = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testInit() throws Exception {
    // JUnitDoclet begin method init
    // JUnitDoclet end method init
  }
  
  public void testHandleMessage() throws Exception {
    // JUnitDoclet begin method handleMessage
    // 1. Update stats re message transfer
    // 2. Check whether message has been seen
    // 3. Update node activity stats
    // 4. remove message from previous nodes message box ??
    // 5. check for a local match
    // 6. check message TTL
    // 7. add message to all connected nodes (except the one we received from )
    // each of the above should be individual methods that we test ...

    SimpleKeyword[][] x_keywords = new SimpleKeyword[4][3];
    Node x_node[] = new NeuroGridNode[4];
    for(int i=0;i<4;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
      x_node[i] = new NeuroGridNode(neurogridnetwork,new Random(888));
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new SimpleContentMessage[3];

    Node neurogridnode = new NeuroGridNode(neurogridnetwork,new Random(888));
    
    
    neurogridnode.addConnection(x_node[0]);
    neurogridnode.addConnection(x_node[1]);
    neurogridnode.addConnection(x_node[2]);
    neurogridnode.addConnection(x_node[3]);
    
    SimpleKeyword[] x_query = new SimpleKeyword[6]; 
    x_query[0] = x_keywords[0][0];
    x_query[1] = x_keywords[0][1];
    x_query[2] = x_keywords[1][0];
    x_query[3] = x_keywords[1][1];
    x_query[4] = x_keywords[2][0];
    x_query[5] = x_keywords[3][0];
    
    SimpleKeyword[] x_unrelated_query = new SimpleKeyword[6]; 
    for(int i=0;i<6;i++)
    { 
      x_unrelated_query[i] = new SimpleKeyword();
    }

    // need to set up some knowledge in NG network

    neurogridnode.addKnowledge(x_node[0], x_keywords[0]);
    neurogridnode.addKnowledge(x_node[1], x_keywords[1]);
    neurogridnode.addKnowledge(x_node[2], x_keywords[2]);
    neurogridnode.addKnowledge(x_node[3], x_keywords[3]);
    
    neurogridnetwork.o_min_forwarding_degree = 1;
    neurogridnetwork.o_max_forwarding_degree = 2;
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_query);	
      x_message[k] = new SimpleContentMessage(3,x_query,x_doc[k],x_node[3]);
      x_message[k].setPreviousLocation(x_node[3]);
    }

    neurogridnode.addContent(x_doc[0]);  
    
    assertTrue("failed to successfully handle message",
               neurogridmessagehandler.handleMessage(x_message[1],neurogridnode));

    assertTrue("node not activated",neurogridnode.getActive());

    assertTrue("Connected knowledgable Node failed to receive message of correct type",
               x_node[0].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.SimpleContentMessage"));
    assertTrue("Connected knowledgable Node failed to receive message of correct type",
               x_node[1].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.SimpleContentMessage"));
    assertTrue("Connected Node exceeding max forward degree received message",
               x_node[2].inboxContainsMessage(x_message[1]) == null);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message[1]) == null);
    assertTrue("initial node still has message",
               neurogridnode.inboxContainsMessage(x_message[1]) == null);

    for(int i=0;i<4;i++)
    {
      x_node[i].clearInbox();
    }	               
               
    ContentMessage x_unrelated_message = new SimpleContentMessage(3,
                                                    x_unrelated_query,
                                                    new SimpleDocument(x_unrelated_query),
                                                    x_node[3]);
    x_unrelated_message.setPreviousLocation(x_node[3]);        

    assertTrue("failed to successfully handle message",
               neurogridmessagehandler.handleMessage(x_unrelated_message,neurogridnode));
               
    int x_no_messages = 0;           
               
    if(x_node[0].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;
    if(x_node[1].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;
    if(x_node[2].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;          
               
    assertTrue("unrelated query not forwarded to only one connected node, x_no_messages="+x_no_messages,
               x_no_messages==1);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message[1]) == null);
    assertTrue("initial node still has message",
               neurogridnode.inboxContainsMessage(x_message[1]) == null);
               
    // need to make sure the message is only received by a single node - although we don't know which 
    // one --> might be good to force some randomness here (from NG point of view) - by here I mean in 
    // the NeuroGridMessageHandler

    // not sure if this last makes sense if we are not passing
    // through inbox to begin with ...           
               
    // outstanding question is how many variations do we check here ...?
    // I guess we need to check all four possible outcomes ...?
    // maybe leave that till later as we really need to get this
    // dishonest network working                
    
    
    
    
    // having done that we need to test the combined methods through the handleMessage
    // method of the handler, then the node and then start looking at how to construct a
    // network given the new approach to messages (i.e. not creating new objects)
    // and the handlers etc.
    
    // JUnitDoclet end method handleMessage
  }

  
  public void testHandleFuzzyMessage() throws Exception {
    // JUnitDoclet begin method handleFuzzyMessage

    SimpleKeyword[][] x_keywords = new SimpleKeyword[4][3];
    Node x_node[] = new NeuroGridNode[4];
    for(int i=0;i<4;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
      x_node[i] = new NeuroGridNode(neurogridnetwork,new Random(888));
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new FuzzyContentMessage[3];

    Node neurogridnode = new NeuroGridNode(neurogridnetwork,new Random(888));
    
    
    neurogridnode.addConnection(x_node[0]);
    neurogridnode.addConnection(x_node[1]);
    neurogridnode.addConnection(x_node[2]);
    neurogridnode.addConnection(x_node[3]);
    
    SimpleKeyword[] x_query = new SimpleKeyword[6]; 
    x_query[0] = x_keywords[0][0];
    x_query[1] = x_keywords[0][1];
    x_query[2] = x_keywords[1][0];
    x_query[3] = x_keywords[1][1];
    x_query[4] = x_keywords[2][0];
    x_query[5] = x_keywords[3][0];
    
    SimpleKeyword[] x_unrelated_query = new SimpleKeyword[6]; 
    for(int i=0;i<6;i++)
    { 
      x_unrelated_query[i] = new SimpleKeyword();
    }

    // need to set up some knowledge in NG network

    neurogridnode.addKnowledge(x_node[0], x_keywords[0]);
    neurogridnode.addKnowledge(x_node[1], x_keywords[1]);
    neurogridnode.addKnowledge(x_node[2], x_keywords[2]);
    neurogridnode.addKnowledge(x_node[3], x_keywords[3]);
    
    neurogridnetwork.o_min_forwarding_degree = 1;
    neurogridnetwork.o_max_forwarding_degree = 2;
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_query);	
      x_message[k] = new FuzzyContentMessage(3,x_query,x_node[3]);
      x_message[k].setPreviousLocation(x_node[3]);
    }

    neurogridnode.addContent(x_doc[0]);  
    
    assertTrue("failed to successfully handle message",
               neurogridmessagehandler.handleMessage(x_message[1],neurogridnode));

    assertTrue("node not activated",neurogridnode.getActive());

    assertTrue("Connected knowledgable Node failed to receive message of correct type",
               x_node[0].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.FuzzyContentMessage"));
    assertTrue("Connected knowledgable Node failed to receive message of correct type",
               x_node[1].inboxContainsMessage(x_message[1]).equals("com.neurogrid.simulation.FuzzyContentMessage"));
    assertTrue("Connected Node exceeding max forward degree received message",
               x_node[2].inboxContainsMessage(x_message[1]) == null);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message[1]) == null);
    assertTrue("initial node still has message",
               neurogridnode.inboxContainsMessage(x_message[1]) == null);

    for(int i=0;i<4;i++)
    {
      x_node[i].clearInbox();
    }	               
               
    ContentMessage x_unrelated_message = new FuzzyContentMessage(3,
                                                   x_unrelated_query,
                                                   x_node[3]);
    x_unrelated_message.setPreviousLocation(x_node[3]);        

    assertTrue("failed to successfully handle message",
               neurogridmessagehandler.handleMessage(x_unrelated_message,neurogridnode));
               
    int x_no_messages = 0;           
               
    if(x_node[0].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;
    if(x_node[1].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;
    if(x_node[2].inboxContainsMessage(x_unrelated_message) != null) x_no_messages++;          
               
    assertTrue("unrelated query not forwarded to only one connected node, x_no_messages="+x_no_messages,
               x_no_messages==1);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message[1]) == null);
    assertTrue("initial node still has message",
               neurogridnode.inboxContainsMessage(x_message[1]) == null);
               
    // need to make sure the message is only received by a single node - although we don't know which 
    // one --> might be good to force some randomness here (from NG point of view) - by here I mean in 
    // the NeuroGridMessageHandler

    // not sure if this last makes sense if we are not passing
    // through inbox to begin with ...           
               
    // outstanding question is how many variations do we check here ...?
    // I guess we need to check all four possible outcomes ...?
    // maybe leave that till later as we really need to get this
    // dishonest network working                
    
    
    
    
    // having done that we need to test the combined methods through the handleMessage
    // method of the handler, then the node and then start looking at how to construct a
    // network given the new approach to messages (i.e. not creating new objects)
    // and the handlers etc.
    
    // JUnitDoclet end method handleFuzzyMessage
  }


  
  public void testInjectMessage() throws Exception {
    // JUnitDoclet begin method injectMessage

    // 6. check message TTL
    // 7. add message to all connected nodes (except the one we received from )

    // JUnitDoclet end method injectMessage
  }
  
  public void testSeenMessage() throws Exception {
    // JUnitDoclet begin method seenMessage
    // need to put in a message twice in a row to see if 
    // message ids are being stored

    SimpleKeyword[] x_keywords = new SimpleKeyword[10];
    
    for(int i=0;i<10;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	
     
    SimpleDocument x_doc = new SimpleDocument(x_keywords);

    Node x_node = new NeuroGridNode(neurogridnetwork,new Random(888));
    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node);  
    
    assertTrue("unseen message indicated seen",!neurogridmessagehandler.seenMessage(x_message,x_node));
    assertTrue("seen message indicated unseen",neurogridmessagehandler.seenMessage(x_message,x_node));
    
    // JUnitDoclet end method seenMessage
  }
  
  public void testProcessCommit() throws Exception {
    // JUnitDoclet begin method processCommit
    // JUnitDoclet end method processCommit
  }
  
  public void testCheckLocalMatch() throws Exception {
    // JUnitDoclet begin method checkLocalMatch
    
    Keyword[][] x_keywords = new SimpleKeyword[3][3];
    
    for(int i=0;i<3;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new SimpleContentMessage[3];
    Node x_node = new NeuroGridNode(neurogridnetwork,new Random(888)); 
    Node neurogridnode = new NeuroGridNode(neurogridnetwork,new Random(888)); 
    int x_message_ttl = 3;
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_keywords[k]);	
      x_message[k] = new SimpleContentMessage(x_message_ttl,x_doc[k].getKeywords(),x_doc[k],neurogridnode);
    }

    x_node.addContent(x_doc[0]);  
    
    assertTrue("local doc not matched",neurogridmessagehandler.checkLocalMatch(x_message[0],x_node)); 
    assertTrue("absent doc falsely matched",!neurogridmessagehandler.checkLocalMatch(x_message[1],x_node)); 
    assertTrue("absent doc falsely matched",!neurogridmessagehandler.checkLocalMatch(x_message[2],x_node)); 

    assertTrue("number of matches incorrect: ",Network.o_no_matches==1);
    assertTrue("number of false matches incorrect",Network.o_no_false_matches==0);
    assertTrue("first ttl incorrect",Network.o_TTL_of_first_match==x_message_ttl);   
    
    // need to check that we make a connection between this node and origin node ... 
    assertTrue("no connection created between two nodes",neurogridnode.hasConnection(x_node));
    // need to check that we updated origin node knowledge base... 
    for(int k=0;k<3;k++)
    {
      assertTrue("no knowledge created for " + x_keywords[0][k],
                 neurogridnode.getRecommendation(x_keywords[0][k]).contains(x_node));
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("incorrect knowledge created for " + x_keywords[1][k],
                 neurogridnode.getRecommendation(x_keywords[1][k])==null);
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("incorrect knowledge created for " + x_keywords[2][k],
                 neurogridnode.getRecommendation(x_keywords[2][k])==null);
    }

    
    // JUnitDoclet end method checkLocalMatch
  }
  
  
  public void testCheckAdversarialLocalMatch() 
    throws Exception 
  {
    // JUnitDoclet begin method checkLocalMatch
    
    Keyword[][] x_keywords = new SimpleKeyword[3][3];
    
    for(int i=0;i<3;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new SimpleContentMessage[3];
    Node x_node = new AdversarialNode(neurogridnetwork, new NeuroGridMessageHandler(new Random(888)),4,0,12); 
    Node neurogridnode = new NeuroGridNode(neurogridnetwork,new Random(888),4,0,12); 
    int x_message_ttl = 3;
    
    neurogridnode.addConnection(x_node);
    assertTrue("no connection created between two nodes",neurogridnode.hasConnection(x_node));
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_keywords[k]);	
      x_message[k] = new SimpleContentMessage(x_message_ttl,x_doc[k].getKeywords(),x_doc[k],neurogridnode);
      neurogridnode.addKnowledge(x_node,x_keywords[k]);
    }

    x_node.addContent(x_doc[0]);  
    
    assertTrue("local doc not matched",neurogridmessagehandler.checkLocalMatch(x_message[0],x_node)); 
    assertTrue("absent doc not falsely matched",neurogridmessagehandler.checkLocalMatch(x_message[1],x_node)); 
    assertTrue("absent doc not falsely matched",neurogridmessagehandler.checkLocalMatch(x_message[2],x_node)); 

    assertTrue("number of matches incorrect: ",Network.o_no_matches==3);
    assertTrue("number of false matches incorrect",Network.o_no_false_matches==2);
    assertTrue("first ttl incorrect",Network.o_TTL_of_first_match==x_message_ttl);   
    
    // this can fail depending on the minimu number of connections for the NG node ...
    // need to check that we make a connection between this node and origin node ... 
    assertTrue("connection between two nodes not removed",!neurogridnode.hasConnection(x_node));
    // need to check that we updated origin node knowledge base... 
    for(int k=0;k<3;k++)
    {
      assertTrue("correct knowledge removed " + x_keywords[0][k],
                 neurogridnode.getRecommendation(x_keywords[0][k]).contains(x_node));
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("knowledge not removed " + x_keywords[1][k],
                 neurogridnode.getRecommendation(x_keywords[1][k])==null);
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("knowledge not removed " + x_keywords[2][k],
                 neurogridnode.getRecommendation(x_keywords[2][k])==null);
    }

    
    // JUnitDoclet end method checkLocalMatch
  }
  
  
  public void testCheckFuzzyLocalMatch() throws Exception {
    // JUnitDoclet begin method checkFuzzyLocalMatch
    
    SimpleKeyword[][] x_keywords = new SimpleKeyword[3][3];
    
    for(int i=0;i<3;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new FuzzyContentMessage[3];
    Node x_node = new NeuroGridNode(neurogridnetwork,new Random(888)); 
    Node neurogridnode = new NeuroGridNode(neurogridnetwork,new Random(888)); 
    int x_message_ttl = 3;
     
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_keywords[k]);	
      x_message[k] = new FuzzyContentMessage(x_message_ttl,x_doc[k].getKeywords(),neurogridnode);
    }

    x_node.addContent(x_doc[0]);  
    
    assertTrue("local doc not matched",neurogridmessagehandler.checkFuzzyLocalMatch(x_message[0],x_node)); 
    assertTrue("absent doc falsely matched",!neurogridmessagehandler.checkFuzzyLocalMatch(x_message[1],x_node)); 
    assertTrue("absent doc falsely matched",!neurogridmessagehandler.checkFuzzyLocalMatch(x_message[2],x_node)); 
    
    
    System.out.println("Network.o_no_matches: "+Network.o_no_matches);
    System.out.println("Network.o_no_false_matches: "+Network.o_no_false_matches);
    System.out.println("Network.o_TTL_of_first_match: "+Network.o_TTL_of_first_match); 
      
    assertTrue("number of matches incorrect: ",Network.o_no_matches==1);
    assertTrue("number of false matches incorrect",Network.o_no_false_matches==0);
    assertTrue("first ttl incorrect",Network.o_TTL_of_first_match==x_message_ttl);      

    // need to check that we make a connection between this node and origin node ... 
    assertTrue("no connection created between two nodes",neurogridnode.hasConnection(x_node));
    // need to check that we updated origin node knowledge base... 
    for(int k=0;k<3;k++)
    {
      assertTrue("no knowledge created for " + x_keywords[0][k],
                 neurogridnode.getRecommendation(x_keywords[0][k]).contains(x_node));
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("incorrect knowledge created for " + x_keywords[1][k],
                 neurogridnode.getRecommendation(x_keywords[1][k])==null);
    }

    for(int k=0;k<3;k++)
    {
      assertTrue("incorrect knowledge created for " + x_keywords[2][k],
                 neurogridnode.getRecommendation(x_keywords[2][k])==null);
    }

    // JUnitDoclet end method checkFuzzyLocalMatch
  }
  
  public void testCheckMessageTTL() throws Exception {
    // JUnitDoclet begin method checkMessageTTL

    SimpleKeyword[][] x_keywords = new SimpleKeyword[3][3];
    
    for(int i=0;i<3;i++)
    {
      for(int j=0;j<3;j++)
      {
        x_keywords[i][j] = new SimpleKeyword();	
      }
    }	
     
    SimpleDocument[] x_doc = new SimpleDocument[3];
    ContentMessage x_message[] = new SimpleContentMessage[3];
    Node x_node = new NeuroGridNode(neurogridnetwork,new Random(888)); 
    
    for(int k=0;k<3;k++)
    {
      x_doc[k] = new SimpleDocument(x_keywords[k]);	
      x_message[k] = new SimpleContentMessage((k==0?1:k),x_doc[k].getKeywords(),x_doc[k],x_node);
    }
    
    //create messages with TTL of 1 and not 1 and check we get the right responses
    
    //assertTrue("TTL less than one accepted",!neurogridmessagehandler.checkMessageTTL(x_message[0],x_node));
    assertTrue("TTL of one accepted",!neurogridmessagehandler.checkMessageTTL(x_message[1],x_node));
    assertTrue("TTL greater than one rejected",neurogridmessagehandler.checkMessageTTL(x_message[2],x_node));
    
    // JUnitDoclet end method checkMessageTTL
  }
  
  public void testForwardMessage() throws Exception {
    // JUnitDoclet begin method forwardMessage
    // we should check that the message is passed to all the nodes connected to a single node

    Node x_node[] = new NeuroGridNode[4];
    for(int i=0;i<4;i++)
    {
      x_node[i] = new NeuroGridNode(neurogridnetwork,new Random(888));
    }
    
    
    x_node[0].addConnection(x_node[1]);
    x_node[0].addConnection(x_node[2]);
    x_node[0].addConnection(x_node[3]);
    
    SimpleKeyword[] x_keywords = new SimpleKeyword[10];
    
    for(int i=0;i<10;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	

    // need to set up some knowledge in NG network

    x_node[0].addKnowledge(x_node[1], x_keywords);

     
    SimpleDocument x_doc = new SimpleDocument(x_keywords);

    ContentMessage x_message = new SimpleContentMessage(3,x_doc.getKeywords(),x_doc,x_node[3]); 
    x_message.setPreviousLocation(x_node[3]);
    
    // also need to set the forwarding degree ...
    
    neurogridmessagehandler.forwardMessage(x_message,x_node[0]);
    
    assertTrue("Connected knowledgable Node failed to receive message of correct type",
               x_node[1].inboxContainsMessage(x_message).equals("com.neurogrid.simulation.SimpleContentMessage"));
    assertTrue("Connected unknowledgable Node received message",
               x_node[2].inboxContainsMessage(x_message)==null);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message) == null);

    
    // JUnitDoclet end method forwardMessage
  }
    
  public void testForwardFuzzyMessage() throws Exception {
    // JUnitDoclet begin method forwardMessage
    // we should check that the message is passed to all the nodes connected to a single node

    Node x_node[] = new NeuroGridNode[4];
    for(int i=0;i<4;i++)
    {
      x_node[i] = new NeuroGridNode(neurogridnetwork,new Random(888));
    }
    
    
    x_node[0].addConnection(x_node[1]);
    x_node[0].addConnection(x_node[2]);
    x_node[0].addConnection(x_node[3]);

    SimpleKeyword[] x_keywords = new SimpleKeyword[10];
    
    for(int i=0;i<10;i++)
    {
      x_keywords[i] = new SimpleKeyword();	
    }	

    // need to set up some knowledge in NG network

    x_node[0].addKnowledge(x_node[1], x_keywords);
     
    SimpleDocument x_doc = new SimpleDocument(x_keywords);

    ContentMessage x_message = new FuzzyContentMessage(3,x_doc.getKeywords(),x_node[3]); 
    x_message.setPreviousLocation(x_node[3]);
    
    neurogridmessagehandler.forwardMessage(x_message,x_node[0]);
    
    assertTrue("Connected Node failed to receive message of correct type",
               x_node[1].inboxContainsMessage(x_message).equals("com.neurogrid.simulation.FuzzyContentMessage"));
    assertTrue("Connected unknowledgable Node received message",
               x_node[2].inboxContainsMessage(x_message)==null);
    assertTrue("Connected Node that sent message re-received message",
               x_node[3].inboxContainsMessage(x_message) == null);
               
    // this fails to check the type of message

    
    // JUnitDoclet end method forwardMessage
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    String x_method = System.getProperty("test.method");
    System.out.println("test.method="+x_method);
    if(x_method == null || x_method.equals(""))
    {
      System.out.println("testing all methods");
    
      junit.textui.TestRunner.run(NeuroGridMessageHandlerTest.class);
    }
    else
    {
      System.out.println("testing single method");

      TestSuite suite = new TestSuite();
      suite.addTest(new NeuroGridMessageHandlerTest(x_method));
      junit.textui.TestRunner.run(suite);
    }    // JUnitDoclet end method testcase.main
  }
}
